config/routes.rb
Rails.application.routes.draw do
  # get 'rooms/index'
  #
  # get 'rooms/show'
  #
  # get 'rooms/new'
  #
  # get 'rooms/create'
  #
  # get 'rooms/edit'
  #
  # get 'rooms/update'
  #
  root 'pages#home'
  devise_for :users,
      :path => '',
      :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
      :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
                    :registrations => 'registrations'}

  resources :users, only: [:show]
  resources :rooms
  resources :photos
  resources :rooms do
      resources :reservations, only: [:create]
  end

  get '/preload' => "reservations#preload"
  get '/your_trips' => "reservations#your_trips"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :reservations

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :home_typing, :accommodate, :bed_room, :bath_room, :listing_name, :summary, :address, presence: true
  validates :address, length: {maximum: 50}
  validates :summary, length: {maximum: 1000}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  validates :first_name, :last_name, presence: true, length: {minimum: 2}
  has_many :rooms
  has_many :reservations

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first
    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.first_name = auth.info.first_name
        user.last_name = auth.info.last_name
        user.email = auth.info.email
        user.image = auth.info.image
        user.password = Devise.friendly_token[0,20]
    end
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number, :description, :email, :password])
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def destroy
    @photo = Photo.find(params[:id])
    room = @photo.room

    @photo.destroy
    @photos = Photo.where(room_id: room.id)

    respond_to :js
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!


  def preload
    room = Room.find(params[:room_id])
    today = Date.today
    reservations = room.reservations.where("start_date > = ? OR end_date>= ?", today, today)
    render json: reservations

  end

  def create
    @reservation = current_user.reservations.create(reservation_params)
    redirect_to @reservation.room, notice: "Your reservations has been created..."
  end

  def your_trips
    @trips = current_user.reservations
    
  end

  private
  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :price, :total, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update]
  before_action :authenticate_user!, except:[:show]
  def index
    @room = current_user.rooms
  end

  def show
    @photos = @room.photos
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)

    if @room.save

      if params[:images]
        params[:images].each do |image|
          @room.photos.create(image: image)
        end
      end

      @photos = @room.photos
      redirect_to edit_room_path(@room), notice: "Saved..."
    else
      render :new
    end
  end

  def edit
    if current_user.id == @room.user.id
      @photos = @room.photos
    else
      redirect_to root_path, notice: "You don't have permission"
    end
  end

  def update
    if @room.update(room_params)

      if params[:images]
        params[:images].each do |image|
          @room.photos.create(image: image)
        end
      end
      redirect_to edit_room_path(@room), notice: "Update..."
    else
      render :edit
    end
  end

  protected
  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:home_typing, :room_type, :accommodate, :bed_room, :bath_room, :listing_name, :summary, :address, :is_tv, :is_kitchen, :is_air, :is_heating, :is_internet, :price, :active)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
    <title>GetRoom</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'shared/navbar'%>
    <%= render 'shared/message'%>

    <div class="container">
      <br>
      <br>
      <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-md-9">
    <h1>Welcome to GetRoom!</h1>
  </div>
</div>

app/views/photos/_list.html.erb
<% if @photos %>

  <div class="row">
    <% @photos.each do |photo| %>
      <div class="col-md-4" id ="rasm">
        <div class="panel panel-default">
          <div class="panel-heading preview">
            <%= image_tag photo.image.url() %>
          </div>
          <div class="panel-body">
            <span class = "pull-right">
              <%= link_to photo, remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
                <i class = "fa fa-times fa-lg"></i>
              <% end %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos/list'%>")

app/views/reservations/_form.html.erb
<%= form_for([@room, @room.reservations.new]) do |f|%>
  <div class="row">
    <div class="col-md-6">
        <label>Checkin</label>
        <%= f.text_field :start_date, placeholder: "Start Date", class: 'start_date'%>
    </div>
    <div class="col-md-6">
        <label id = "end_label">Checkout</label>
        <%= f.text_field :end_date, placeholder: "End Date", class: "end_date"%>
    </div>
  </div>




  <%= f.hidden_field :room_id, value: @room.id%>
  <%= f.hidden_field :price, value: @room.price%>
  <%= f.hidden_field :total, id: 'reservation_total'%>

  <div class="preview" style = "display: none">
    <h4><span id="message"></span></h4>

    <table class="reservation-table">
      <tbody>
        <tr>
          <td>Day(s)</td>
          <td><span id = "reservation-days"></span></td>
        </tr>
        <tr>
          <td>Total</td>
          <td><span id="reservation_sum"></span></td>

        </tr>
      </tbody>

    </table>
  </div>

  <br>
  <%= f.submit "Book Now", class: "btn btn-danger"%>
<% end %>


<script type="text/javascript">
    $(function(){
      $.ajax({
        url: '/preload',
        data: {'room_id': <%= @room.id %>},
        dataType: 'json',
        success: function(data){
          $.each(data, function(arrID, arrValue){
            for(var i = new Date(arrValue.start_date); i <= new Date(arrValue.end_date); i.setDate(i.getDate()+1)){
              console.log(i);
            }

          })
        }

      })


      $('#reservation_start_date').datepicker({
        dateFormat: "dd-mm-yy"
      })
      $('#reservation_end_date').datepicker({
        dateFormat: "dd-mm-yy"
      })
    })
</script>

app/views/reservations/your_trips.html.erb
<h2>..</h2>
<div class="row">
  <div class="col-md-3">
    <ul class = "sidebar-list">
      <li class = "sidebar-item"><%= link_to "Your Listing", rooms_path, class: "sidebar-link active"%></li>
      <li class = "sidebar-item"><%= link_to "Your Reservation", rooms_path, class: "sidebar-link"%></li>
      <li class = "sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link active"%></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Your Trips
      </div>
      <div class="panel-body">
        <% @trips.each do |trips| %>
          <div class="row">
            <div class="col-md-2">
              <%= @trips.start_date%>
            </div>
            <div class="col-md-2">
              <%= image_tag trip.room.photos[0].image.url(:thumb)%>
            </div>
            <div class="col-md-2">
              <i class="fa fa-user-secret" aria-hidden="true"></i>
            </div>
            <div class="col-md-2">
              <h4><%= trip.total%></h4>
            </div>
          </div>
          <hr>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/rooms/_form.html.erb
<div class="panel panel-default">
  <h4>gello</h4>
  <div class="panel-heading">
    <h3>Rent out your room and start making money...</h3>
  </div>
  <div class="panel-body">
    <div class="container">

        <%= form_for @room, html: {multipart: true} do |f|%>
          <div class="row">
            <div class="col-md-4 select">
              <div class="form-group">
                <label>Home Type</label>
                <%=f.select :home_typing, [["Apartment", "Apartment"], ["House","House"], ["Bed&Breakfast","Bed&Breakfast"]], id: "home_typing", prompt:"Select...", class: "form-control"%>
              </div>
            </div>

            <div class="col-md-4 select">
              <div class="form-group">
                <label>Room Type</label>
                <%=f.select :room_type, [["Entire", "Entire"], ["Private","Private"], ["Shared","Shared"]],  prompt:"Select...",class: "form-control"%>
              </div>
            </div>

            <div class="col-md-4 select">
              <div class="form-group">
                <label>Accommodate</label>
                <%=f.select :accommodate, [["1", 1], ["2", 2], ["3", 3],["4", 4], ["5", 5], ["6+", 6]], prompt:"Select...",class: "form-control"%>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4 select">
              <div class="form-group">
                <label>Bedrooms</label>
                <%=f.select :bed_room, [["1",1],["2",2],["3",3],["4+",4]], prompt:"Select...",class: "form-control"%>

                  <label>Bathrooms</label>
                  <%=f.select :bath_room, [["1",1],["2",2],["3",3],["4+",4]], prompt:"Select...",class: "form-control"%>

              </div>

            </div>
          </div>

          <div class="row">
            <div class="col-md-4 select">

            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <label>Listing Name</label>
              <%=f.text_field :listing_name, placeholder: "Be clear and descriptive", class: "form-control"%>
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <label>Summary</label>
              <%=f.text_area :summary, rows: 5, placeholder: "Tell about your house", class: "form-control"%>
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <label>Address</label>
              <%=f.text_area :address,  placeholder: "What is your address?", class: "form-control"%>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <%=f.check_box :is_tv%> TV ----->
                <%=f.check_box :is_kitchen%> Kitchen----->
                <%=f.check_box :is_heating%> Heating----->
                <%=f.check_box :is_internet%> Internet----->
                <%=f.check_box :is_air%> Air Conditioning
              </div>
              <div class="form-group">

              </div>
              <div class="form-group">

              </div>
              <div class="form-group">

              </div>
              <div class="form-group">

              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <label>Nightly Price</label>
                <div class="input-group">
                  <div class="input-group-addon">$</div>
                  <%=f.text_field :price, placeholder: "eg. $100", class: "form-control", id: "price"%>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <span class ="btn btn-default btn-file">
                  <i class = "fa fa-cloud-upload fa-lg"></i>Upload Photos
                  <%= file_field_tag "images[]", type: :file, multiple: true %>
                </span>
              </div>
            </div>
          </div>

          <div id = "photos">
            <%= render 'photos/list'%>

          </div>

          <div class="row">
            <div class="form-group">
                <%=f.check_box :active%> Active
            </div>
          </div>

          <div class="actions">
            <%=f.submit "Save", class: "btn btn-primary "%>
          </div>
    <% end %>
  </div>
</div>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/edit.html.erb
<%= render 'form'%>

app/views/rooms/index.html.erb
<h2>..</h2>
<div class="row">
  <div class="col-md-3">
    <ul class = "sidebar-list">
      <li class = "sidebar-item"><%= link_to "Your Listing", rooms_path, class: "sidebar-link active"%></li>
      <li class = "sidebar-item"><%= link_to "Your Reservation", rooms_path, class: "sidebar-link"%></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Listings
      </div>
      <div class="panel-body">
        <% @room.each do |room| %>
          <div class="row">
            <div class="col-md-2">
              <%= image_tag room.photos[0].image.url(:thumb) if room.photos.length > 0%>
            </div>
            <div class="col-md-7">
              <h4><%= room.listing_name%></h4>
            </div>
            <div class="col-md-3 right">
              <%= link_to "Update", edit_room_path(room), class: "btn btn-primary"%>
            </div>
          </div>
          <hr>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/rooms/new.html.erb
<%= render 'form'%>

app/views/rooms/show.html.erb
<h2>..</h2>

<div class="panel panel-default">
  <div class="panel-body">
  <!-- ------------------------IMAGE---------------- -->
    <div class="row-center">
      <div class="col-md-12">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->

          <% if @photos%>
              <ol class="carousel-indicators">
                <% @photos.each do |photo|%>
                  <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"  ></li>
                <% end %>
              </ol>
          <% end %>

          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox" >
            <% if @photos %>
              <% @photos.each do |photo|%>
                <div class="item <%= 'active' if photo.id == @photos[0].id%>" >
                  <%= image_tag photo.image.url(), :class => "carousel_img"%>
                </div>
              <% end %>
            <% end %>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>

    <!-- ------------------------MAIN INFO---------------- -->
    <div class="row">
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-3"><br><br>
            <i class = "fa fa-user-circle-o  fa-5x"></i>
            <h4><%= current_user.first_name%></h4>
            <h4><%= current_user.last_name%></h4>
          </div>
          <br>
          <div class="col-md-9">
            <h4><%= @room.listing_name%></h4>
            <%= @room.address%><br><br>
            <div class="row text-center row-space-1">
              <div class="col-sm-3">
                <i class = "fa fa-home fa-2x"></i>
              </div>
              <div class="col-sm-3">
                <i class = "fa fa-users fa-2x"></i>
              </div>
              <div class="col-sm-3">
                <i class = "fa fa-bed fa-2x"></i>
              </div>
              <div class="col-sm-3">
                <i class = "fa fa-ship fa-2x"></i>
              </div>


              <!-- <div class="col-sm-3" id = "user_icon">
                <i class = "fa fa-users fa-2x"></i>
              </div> -->

              <!-- <div class="col-sm-3" id = "money_icon">
                <i class = "fa fa-tag fa-2x"></i>
              </div> -->
            </div><br>
            <div class="row text-center">
              <div class="col-sm-3">
                <%= @room.home_typing%>
              </div>
              <div class="col-sm-3">
                <%= @room.accommodate%> <%= @room.accommodate > 1? " Guests": " Guest" %>
              </div>
              <div class="col-sm-3">
                <%= @room.bed_room %><%= @room.bed_room > 1? " Bed Rooms": " Bed Room" %>
              </div>
              <div class="col-sm-3">
                <%= @room.bath_room%><%= @room.bath_room > 1? " Bath Rooms": " Bath Room" %>
              </div>
              <div class="col-sm-3" id = "datepicker">
                <%= render 'reservations/form'%>
              </div>
              <!-- <div class="col-sm-3" id="room_type">
                <%= @room.room_type%>
              </div> -->

              <!-- <div class="col-sm-3" id="price_tag">
                <%= @room.price%> $
              </div> -->


            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <!-- ------------------------RESERVATION---------------- -->
      </div>
    </div>

    <!-- ------------------------ABOUT ---------------- -->
    <div class="row">
      <div class="col-md-12">
        <h4>About This Listing</h4>
        <p><%=@room.summary%></p>
      </div>
    </div>
    <hr>

    <!-- ------------------------AMENITIES ---------------- -->
    <div class="row">
      <div class="col-md-2">
        <h3>Amenities</h3>
      </div>
      <div class="col-md-10">
        <div class="col-md-6">
          <ul class = "amenities">
            <li class = "<%= 'text-line-through' if !@room.is_tv %>">TV</li>
            <li class = "<%= 'text-line-through' if !@room.is_kitchen %>">Kitchen</li>
            <li class = "<%= 'text-line-through' if !@room.is_internet %>">Internet</li>


        </div>
        <div class="col-md-6">
          <li class = "<%= 'text-line-through' if !@room.is_air %>">Air Conditioning</li>
          <li class = "<%= 'text-line-through' if !@room.is_heating %>">Heating</li>
        </div>
        </ul>
      </div>
    </div>



    <hr>
    <div class="row">
      <div class="col-md-12">
        <div id="map"></div>
        <style>
          #map {
            height: 400px;
            width: 100%;
           }
        </style>
        <script>
          function initMap() {
            var uluru = { lat: <%=@room.latitude%>, lng: <%= @room.longitude %>};
            var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 14,
              center: uluru
            });
            var marker = new google.maps.Marker({
              position: uluru,
              map: map,
              title: "hello"
            });
          }
        </script>
        <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB_ccVZS7lu5ahdGK9f73vuq8Sbl6X4FqU&callback=initMap">
        </script>
      </div>
    </div>
    <hr>
    <h3>Near By Renting Places</h3>
    <div class="row">
      <% for room in @room.nearbys(10)%>
        <div class="col-md-3">
          <div class="panel panel-default">
            <div class="panel-heading ">
              <%= image_tag room.photos[0].image.url(:medium), :class => "nearby_img"%>
            </div>
            <div class="panel-body">
              <%= link_to room.listing_name, room%><br>
              (<%= room.distance.round(2)%> miles away)
            </div>





          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
  <!-- var uluru = {<%= @room.latitude %>, <%= @room.longitude %>}; -->
<!-- AIzaSyB_ccVZS7lu5ahdGK9f73vuq8Sbl6X4FqU -->

app/views/rooms/update.html.erb
<h1>Rooms#update</h1>
<p>Find me in app/views/rooms/update.html.erb</p>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f|%>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info')%>
      toastr['<%= type %>']('<%= f[1]%>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
 <div class="container">
   <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="#">AirBnB</a>
   </div>
   <div id="navbar" class="navbar-collapse collapse">
     <ul class="nav navbar-nav navbar-right">

       <% if (!user_signed_in?)%>
          <li><%= link_to "Log In", new_user_session_path%></li>
          <li><%= link_to "Sign Up", new_user_registration_path%></li>

      <% else %>

          <li class="dropdown">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name %> <%=current_user.last_name%><span class="caret"></span>  </a>

            <ul class="dropdown-menu ">
              <li><a href="#">Trips</a></li>
              <li><a href="#">Wish List</a></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path%></li>
              <li role="separator" class="divider"></li>
              <li class="dropdown-header">Account Settings</li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete%></li>
            </ul>
          </li>

        <li>
          <a href="#"><i class="fa fa-envelope-o" aria-hidden="true"></i> Message</a>
        </li>
        <li>
          <a href="#"><i class="fa fa-home fa-lg" aria-hidden="true"></i> Become a Host</a>
        </li>
      <% end %>
    </ul>


   </div>
 </div>
</nav>

app/views/shared/_oshibki.html.erb
<% unless resource.errors.empty?%>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |message|%>
      toastr.error('<%= message%>')
    <% end %>
  </script>
<% end %>

app/views/users/show.html.erb
<h2>Hello</h2>
<div class="row">
  <div class="col-md-3">
    <div class="panel panel-default">
      <div class="panel-heading">Verification</div>
      <div class="panel-body">
        Email Address <br>
        Phone Number
      </div>
    </div>
  </div>

  <div class="col-md-9">
    <h2><%= @user.first_name%> <%= @user.last_name%></h2>
    <div class="description row-space-3">
      <%= @user.description%>
    </div>
  </div>
</div>